apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 443
      nodePort: 30443
